steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/retainiq/retainiq:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/retainiq/retainiq:latest'
      - '.'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/retainiq/retainiq'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'retainiq'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/retainiq/retainiq:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=3'
      - '--port=8080'
      - '--set-secrets=ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,GCP_SERVICE_ACCOUNT_JSON=GCP_SERVICE_ACCOUNT_JSON:latest'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/retainiq/retainiq:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/retainiq/retainiq:latest'

options:
  logging: CLOUD_LOGGING_ONLY
